/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiRedesignRouteImport } from './routes/api/redesign'
import { Route as FeaturesFeatureIdRouteImport } from './routes/features.$featureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedesignRoute = ApiRedesignRouteImport.update({
  id: '/api/redesign',
  path: '/api/redesign',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesFeatureIdRoute = FeaturesFeatureIdRouteImport.update({
  id: '/features/$featureId',
  path: '/features/$featureId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/redesign': typeof ApiRedesignRoute
  '/features/$featureId': typeof FeaturesFeatureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/redesign': typeof ApiRedesignRoute
  '/features/$featureId': typeof FeaturesFeatureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/redesign': typeof ApiRedesignRoute
  '/features/$featureId': typeof FeaturesFeatureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/studio' | '/api/redesign' | '/features/$featureId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studio' | '/api/redesign' | '/features/$featureId'
  id: '__root__' | '/' | '/studio' | '/api/redesign' | '/features/$featureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRoute
  ApiRedesignRoute: typeof ApiRedesignRoute
  FeaturesFeatureIdRoute: typeof FeaturesFeatureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/redesign': {
      id: '/api/redesign'
      path: '/api/redesign'
      fullPath: '/api/redesign'
      preLoaderRoute: typeof ApiRedesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$featureId': {
      id: '/features/$featureId'
      path: '/features/$featureId'
      fullPath: '/features/$featureId'
      preLoaderRoute: typeof FeaturesFeatureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRoute,
  ApiRedesignRoute: ApiRedesignRoute,
  FeaturesFeatureIdRoute: FeaturesFeatureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
